name: Build Unsigned Android APK

on:
  workflow_dispatch: 
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Unsigned Release APK
      run: ./gradlew assembleRelease

    - name: Upload Unsigned APK
      uses: actions/upload-artifact@v4
      with:
        name: local_dream-release-unsigned
        # The default output name for an unsigned release build
        path: app/build/outputs/apk/release/app-release-unsigned.apk
